networks:
  app_network:
services:
    frontend:
        # image: oldwhisper/dqfrontend:1.0
        build: ./frontend
        container_name: frontend
        ports:
          - "5173:5173"
        env_file:
         - shared.env
        networks:
         - app_network

    backend:
        # image: oldwhisper/dqbackend:1.0
        build: ./backend
        container_name: backend
        ports:
          - "8081:8081"
        env_file:
         - shared.env
        depends_on:
          - db
        networks:
         - app_network
    
    db:
      image: postgres:latest
      container_name: db
      ports:
       - "5432:5432"
      env_file:
       - shared.env
      restart: always
      shm_size: 128mb
      environment:
       POSTGRES_PASSWORD:  dsaquest
       POSTGRES_USER: admin
       POSTGRES_DB: dsaquest
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      networks:
       - app_network