apiVersion: v1
data:
  BACKEND_PORT: "8081"
  FRONTEND_PORT: "5173"
  POSTGRES_DB: dsaquest
  POSTGRES_PASSWORD: dsaquest
  POSTGRES_URL: postgresql://admin:dsaquest@db:5432/dsaquest
  POSTGRES_USER: admin
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend-shared-env
  name: shared-env
